#!/bin/sh

# Get the data by id

log() {
    echo "$*" 1>&2
}

catURL() {
    curl --stderr /dev/null "$1"
}

dir="$(dirname "$(readlink -f "$0")")"/..

error=0
for id in "$@"; do
    id=${id#ir.collections.}
    pathid=${id#*.}
    what=${id%%.*}

    path="${pathid//.//}"
    fullpath="$dir/eval/$path"
    echo "# $what ($pathid)"

    case "$1" in

	# --- TREC 1-8 (adhoc)
	ir.collections.topics.trec.[1-8].adhoc)
	    mkdir -p "$fullpath"
	    i=${id#topics.trec.}
	    i=${i%.adhoc}
	    v=(0 1-50 51-100 101-150 201-250 251-300 301-350 351-400 401-450)
	    echo "$i"
	    echo "${v[$i]}"
	    catURL "http://trec.nist.gov/data/topics_eng/topics.${v[$i]}.gz" | gunzip -c > "$fullpath/$what"
	    ;;

      # --- TREC 2004 web
	ir.collections.topics.trec.2004.web)
	    mkdir -p "$fullpath"
	    catURL "http://trec.nist.gov/data/web/Web2004.query.stream.trecformat.txt" > "$fullpath/$what"
	    ;;

	ir.collections.qrels.trec.2004.web)
	    mkdir -p "$fullpath"
	    catURL "http://trec.nist.gov/data/web/04.qrels.web.mixed.txt" | sed -e 's/^/WT04-/' > "$fullpath/$what"
	    ;;
	
      # --- TREC 2005 Robust
	ir.collections.qrels.trec.2005.robust)
	    ;;

	*) log "Cannot handle collection $1"; error=1;;
    esac
done

exit $error