#!/bin/sh

# Either returns a list of task, or a task description

dir="$(dirname $(readlink -f "$0"))"

id="$1"
method="!method=xml"
if test "$id" = ""; then
    echo "List of all tasks:"
    echo
    id="-"
    method='!method=text'
fi

java -cp $dir/../lib/saxon8.jar net.sf.saxon.Query $dir/get-task.xq +doc=$dir/../etc/tasks.xml id="$id" "$method"


