#!/bin/sh

# Creates absolute paths

DIR=$(dirname $(dirname $(readlink -f "$0")))
echo "Base directory is $DIR" 1>&2

find $DIR -name "*.col.relfiles" | while read f; do
	echo "  * Writing  ${f/col.rel/col.}"
	sed -e "s#^#$DIR/data/#" $f > ${f/col.rel/col.}
done
